### ISSUE TITLE
Error: Request failed with status code 500

### ISSUE THREAD

**Issue by ilwoonam75** [adityajoshi12/kafka-nodejs#1]
I followed your guide in the link https://www.youtube.com/watch?v=KA2lspfWovE

I successfully produce and consume with the producer.py and consumer.py.

But when I connect kafka from the droid, I got the following error. (Error: Request failed with status code 500)

See attached.

Can you advice me this issue?
![Screenshot from 2021-12-31 23-12-44](https://user-images.githubusercontent.com/11212680/147827753-9552dd86-e2d7-4dd3-92ac-be5d2f040fa5.png)

**Comment by adityajoshi12** [comment]
check if the port is correctly configured.

**Comment by ilwoonam75** [comment]
The problem is I use "localhost".
I solved the problem using IP address instead of localhost.
Thank you.
